version: '3.9'

services:
    web:

        build:
          context: Sarkis/
        container_name: "sarkis-svelte"
        restart: unless-stopped
        working_dir: /app
        volumes:
          - ./Sarkis:/app
        ports:
          - 80:3000
