version: '3.9'

services:
    web:

        build:
          context: sarkis-svelte
        container_name: "sarkis-svelte"
        restart: unless-stopped
        working_dir: /app
        volumes:
          - ./sarkis-svelte:/app
        ports:
          - 80:3000
